FROM pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN buildDeps='gcc libc6-dev make build-essential' \
    && apt-get update && apt-get install -y $buildDeps git wget tar \
    && pip install --upgrade pip 
    
RUN pip install pororo jupyter-tensorboard jupyterlab jupyterlab-system-monitor
RUN jupyter labextension install jupyterlab_tensorboard

EXPOSE 8888

CMD ["sh","-c", "jupyter lab --ip=0.0.0.0 --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*']
