FROM pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN buildDeps='gcc libc6-dev make build-essential curl gnupg' \
    && apt-get update && apt-get install -y $buildDeps git wget tar \
    && pip install --upgrade pip 
    
RUN curl -sL https://deb.nodesource.com/setup_12.x  | bash -
RUN curl -fsSL https://code-server.dev/install.sh | sh
RUN apt-get -y install nodejs
RUN npm install

RUN pip install tornado pytorch-lightning pandas scikit-learn
RUN pip install jupyterlab==2.2.9
RUN pip install pororo jupyter-tensorboard
RUN jupyter labextension install jupyterlab_tensorboard jupyterlab-system-monitor

#load pre-trained model in pororo
RUN python -c "from pororo import Pororo; ner=Pororo(task='ner', lang='ko'); sts=Pororo(task='similarity', lang='ko'); se=Pororo(task='sentence_embedding', lang='ko');"
RUN python -c "from pororo import Pororo; sa=Pororo(task='sentiment', model='brainbert.base.ko.shopping', lang='ko');"
RUN python -c "from pororo import Pororo; summ=Pororo(task='summarization', model='abstractive', lang='ko'); summ=Pororo(task='summarization', model='bullet', lang='ko'); summ=Pororo(task='summarization', model='extractive', lang='ko');"

EXPOSE 8888 8080

CMD ["sh","-c", "jupyter lab --ip=0.0.0.0 --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*'"]
