FROM python:3.8.5-slim

USER root

# change apt source list to kakao
RUN sed -i 's#http://archive.ubuntu.com/ubuntu/#http://mirror.kakao.com/ubuntu/#g' /etc/apt/sources.list
RUN sed -i 's#http://security.ubuntu.com/ubuntu/#http://mirror.kakao.com/ubuntu/#g' /etc/apt/sources.list

RUN buildDeps='gcc libc6-dev make' \
    && apt-get update && apt-get install -y $buildDeps git wget tar vim unzip libaio1 \
    && apt-get install -y --no-install-recommends ca-certificates bash-completion byobu git-core dpkg curl gnupg \
    && curl -sL https://deb.nodesource.com/setup_12.x | bash - \
    && apt-get install -y nodejs \
    && pip3 install --upgrade pip && pip3 install --ignore-installed PyYAML \
    && rm -rf /var/lib/apt/lists/* 

RUN apt-get update && apt-get install -y libkrb5-dev

ENV SHELL /bin/bash

RUN pip3 install sqlalchemy pandas-profiling cx_Oracle boto3 pyathena
RUN pip3 install phoenixdb
RUN pip3 install hdfs

#install node-red & contrib packages
RUN npm install -g --unsafe-perm node-red@1.1.0
RUN npm install -g node-red-contrib-python-function node-red-contrib-loop-processing body-parser node-red-contrib-mongodb3 node-red-contrib-slack node-red-contrib-slack-files node-red-contrib-redis node-red-dashboard
RUN npm install -g node-red-contrib-flow-manager
RUN npm install -g --production node-red-contrib-cache
EXPOSE 1880

#add internal javascript dependency modules
RUN npm install sync-request applicationinsights url-join slack-node

#set python3 as default python version
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 0

WORKDIR /workspace/
COPY settings.js /workspace/settings.js
RUN mkdir -p /root/.node-red/envnodes

#set time-zone as Asia/Seoul
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#spcify oracle jdbc connector
RUN mkdir -p /opt/oracle && cd /opt/oracle && wget https://download.oracle.com/otn_software/linux/instantclient/191000/instantclient-basic-linux.x64-19.10.0.0.0dbru.zip \
 && unzip instantclient-basic-linux.x64-19.10.0.0.0dbru.zip \
 && cd /opt/oracle/instantclient_19_10 
# && ln -s libclntsh.so.12.1 libclntsh.so \
# && ln -s libocci.so.12.1 libocci.so
RUN sh -c "echo /opt/oracle/instantclient_19_10 > /etc/ld.so.conf.d/oracle-instantclient.conf" && ldconfig
RUN export LD_LIBRARY_PATH=/opt/oracle/instantclient_19_10:$LD_LIBRARY_PATH
RUN export PATH=/opt/oracle/instantclient_19_10:$PATH

CMD ["node-red", "-v", "--settings", "settings.js", "--flowFile", "flows.json", "userDir", "."]
