FROM pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
RUN buildDeps='gcc libc6-dev make build-essential curl gnupg' \
    && apt-get update && apt-get install -y $buildDeps git wget tar \
    && pip install --upgrade pip 
    
RUN curl -sL https://deb.nodesource.com/setup_12.x  | bash -
RUN apt-get -y install nodejs
RUN npm install

RUN pip install tornado pytorch-lightning pandas scikit-learn streamlit boto3
RUN pip install jupyterlab==2.2.9
RUN pip install transformers jupyter-tensorboard papermill
RUN jupyter labextension install jupyterlab_tensorboard jupyterlab-system-monitor

#load pre-trained model in koelectra(based on small model)
RUN python -c "from transformers import ElectraModel, ElectraTokenizer; model = ElectraModel.from_pretrained('monologg/koelectra-small-v3-discriminator'); tokenizer = ElectraTokenizer.from_pretrained('monologg/koelectra-small-v3-discriminator');"
RUN python -c "from transformers import ElectraModel, ElectraTokenizer; model = ElectraModel.from_pretrained('monologg/koelectra-base-v3-discriminator'); tokenizer = ElectraTokenizer.from_pretrained('monologg/koelectra-base-v3-discriminator');"

EXPOSE 8888 8080 6006

CMD ["sh","-c", "jupyter lab --ip=0.0.0.0 --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.password='' --NotebookApp.allow_origin='*'"]
